import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import networkx as nx
from scipy.special import k1
from joblib import Parallel, delayed

import triadic_library as triadic


# =============================================================================
# SECTION 1: SHARED THEORETICAL MODEL
# =============================================================================
def theoretical_degree(R: int, c: float, rho_1D: float, d0: float, delta: float) -> float:
    """
    Calculates the exact theoretical structural degree <k> using modified Bessel functions.

    :param R: int, number of rings
    :param c: float, structural connectivity constant
    :param rho_1D: float, 1D linear density
    :param d0: float, characteristic decay length
    :param delta: float, separation between rings
    :return: float, exact mathematical mean degree
    """
    k_tot = 0.0
    for n in range(R):
        dy = min(n, R - n) * delta
        if dy == 0:
            k_tot += 2 * c * rho_1D * d0
        else:
            k_tot += 2 * c * rho_1D * dy * k1(dy / d0)
    return k_tot


def compute_experimental_k(idx: int, d0_test: float, N_per_ring: int, num_rings: int, Lx: float, delta: float, c: float,
                           seed: int) -> tuple:
    """
    Worker function to compute the experimental degree for a given d0 in parallel.

    :param idx: int, index of the current task to maintain order
    :param d0_test: float, characteristic decay length to test
    :param N_per_ring: int, number of nodes per ring
    :param num_rings: int, total number of rings
    :param Lx: float, X-axis length
    :param delta: float, Y-axis separation between rings
    :param c: float, structural connectivity constant
    :param seed: int, random seed
    :return: tuple, containing (index, d0 tested, resulting empirical k)
    """
    np.random.seed(seed)
    _, G, _ = triadic.coupled_rings_structural_network(N_per_ring, num_rings, Lx, delta, c, d0_test)
    k_emp = np.mean([d for n, d in G.degree()])
    return idx, d0_test, k_emp


# =============================================================================
# SECTION 2: GLOBAL INPUTS (ALL AT THE BEGINNING)
# =============================================================================
print("=" * 60)
print("--- STARTING EXPERIMENTAL VALIDATION SUITE ---")
print("=" * 60)

print("\n[1/3] Base Physics Parameters (Press Enter for Defaults):")
raw_n = input("  -> N_per_ring (Default: 1000)      : ").strip()
N_per_ring = int(raw_n) if raw_n else 1000

raw_dens = input("  -> Density 1D (Default: 200.0)     : ").strip()
density = float(raw_dens) if raw_dens else 200.0

raw_c = input("  -> c constant (Default: 0.07)      : ").strip()
c = float(raw_c) if raw_c else 0.07

raw_d0 = input("  -> d0_base (Default: 0.20)         : ").strip()
d0_base = float(raw_d0) if raw_d0 else 0.20

raw_seed = input("  -> Random seed (Default: 42)       : ").strip()
seed = int(raw_seed) if raw_seed else 42

print("\n[2/3] Folder/Directory Setup:")
raw_loop = input("  -> loop_max_rings in folders (e.g. 15 or [30]): ").strip()
loop_max_rings = int(raw_loop) if raw_loop else 30

raw_target = input("  -> target_rings in folders (Default 0): ").strip()
target_rings = int(raw_target) if raw_target else 0

raw_dfacts = input("  -> delta_factors simulated (e.g. 0.005, 0.05, 0.2, 0.5, 1.0, 5.0): ").strip()
dfact_list = [float(d.strip()) for d in raw_dfacts.split(',') if d.strip()] if raw_dfacts else \
    [0.005, 0.05, 0.2, 0.5, 1.0, 5.0]

print("\n[3/3] Experiment Toggles:")
run_loglog = input("  -> Run Log-Log real-time sweep? (Takes more time) (y/n, Default: y): ").strip().lower() != 'n'
if run_loglog:
    raw_dfact_log = input("     -> delta_factor to use for Log-Log (Default: 0.2): ").strip()
    dfact_loglog = float(raw_dfact_log) if raw_dfact_log else 0.2

    raw_num_rings_log = input("     -> num_rings for Log-Log (Default: 100 [Recommended to reach 2D Limit]): ").strip()
    num_rings_log = int(raw_num_rings_log) if raw_num_rings_log else 100

    raw_jobs = input("     -> CPU Cores for parallel Log-Log (Default: 1): ").strip()
    n_jobs_log = int(raw_jobs) if raw_jobs else 1

dir_name = "results/experimental_validation_plots/"
os.makedirs(dir_name, exist_ok=True)
target_str = "None" if target_rings == 0 else str(target_rings)

# =============================================================================
# SECTION 3: EXPERIMENT 1 - DATA LOADING & PLOTTING (NORMALIZED REGIMES)
# =============================================================================
print("\n" + "-" * 30)
print("PROCESSING NORMALIZED REGIMES...")
print("-" * 30)

# Build dynamic paths based on user input
csv_files = {}
for dfact in dfact_list:
    # 1. Calculate actual delta
    delta_val = dfact * d0_base

    # 2. Reconstruct the exact directory name generated by your calibration engine
    target_dir = (f'results/calibration_RINGS_loop{loop_max_rings}_target{target_str}_N{N_per_ring}_dens{density}_c{c}'
                  f'_d0base{d0_base}_dfact{dfact}_seed{seed}/')
    csv_path = os.path.join(target_dir, "calibration_data.csv")
    csv_files[delta_val] = csv_path

# --- PLOT 1: NORMALIZED REGIMES SETUP ---
plt.figure(figsize=(10, 7))
colors = plt.get_cmap('viridis')(np.linspace(0.1, 0.9, len(csv_files)))
files_found = 0

rings_int_regimes = np.arange(1, loop_max_rings + 1)
# Upper Limit: Perfect linear growth (y = x) -> 1D Collapse
plt.plot(rings_int_regimes, rings_int_regimes, color='black', linestyle='--', label='Upper Limit: 1D Collapse')
# Lower Limit: No growth (y = 1) -> Uncoupled
plt.axhline(1.0, color='gray', linestyle='-.', label='Lower Limit: Uncoupled')

for (delta_val, csv_path), color in zip(csv_files.items(), colors):
    try:
        df = pd.read_csv(csv_path)
        files_found += 1

        r_range = np.arange(1, df['num_rings'].max() + 1)

        # Experimental points (normalized by the degree of the first ring)
        k_norm_exp = df['k_unscaled'] / df['k_unscaled'].iloc[0]
        plt.plot(df['num_rings'], k_norm_exp, marker='o', linestyle='', color=color,
                 markersize=7, alpha=0.8, markeredgecolor='black', label=rf'Exp. $\Delta={delta_val:.3f}$')

        # Theoretical continuous curve (normalized)
        k_theo_norm = [
            theoretical_degree(r, c, density, d0_base, delta_val) / theoretical_degree(1, c, density, d0_base,
                                                                                       delta_val) for r in r_range]
        plt.plot(r_range, k_theo_norm, color=color, linestyle='-', alpha=0.5)

    except FileNotFoundError:
        print(f"  -> Warning: Folder not found for delta {delta_val:.3f}")

# Finalizing and saving Plot 1
if files_found > 0:
    plt.xlim(left=0.5)
    plt.grid(True, linestyle=':', alpha=0.6)
    plt.xlabel("Number of Rings (R)")
    plt.ylabel("Growth Factor (k_R / k_1)")
    plt.legend()
    plt.savefig(os.path.join(dir_name, "plot_1_regimes.png"), dpi=400)
    print("  -> plot_1_regimes.png saved successfully.")
    plt.close()
else:
    print("  -> Skipped Plot 1 (No CSV files found).")

# =============================================================================
# SECTION 4: EXPERIMENT 2 - LOG-LOG SWEEP
# =============================================================================
if run_loglog:
    print("\n" + "-" * 30)
    print("RUNNING LOG-LOG SWEEP...")
    print("-" * 30)

    delta_log = dfact_loglog * d0_base
    Lx = N_per_ring / density

    # Generate an array of d0 values in logarithmic scale (from ~0.005 to ~0.4)
    d0_array = np.logspace(-2.3, -0.4, 15)

    # Initialize array to hold results maintaining the order
    k_exp_log = [0.0] * len(d0_array)

    print(f"  -> Dispatching {len(d0_array)} tasks to Joblib (n_jobs={n_jobs_log})...")
    with Parallel(n_jobs=n_jobs_log, return_as="generator") as parallel:
        results_generator = parallel(
            delayed(compute_experimental_k)(i, d0_t, N_per_ring, num_rings_log, Lx, delta_log, c, seed)
            for i, d0_t in enumerate(d0_array)
        )

        for res in results_generator:
            idx, d0_val, k_emp = res
            print(f"     -> Finished d0 = {d0_val:.4f} (Resulting <k> = {k_emp:.4f})")
            k_exp_log[idx] = k_emp

    print("  -> Generating Log-Log Plot...")

    plt.figure(figsize=(9, 6))

    # High-resolution theoretical line
    d0_smooth = np.logspace(-2.5, -0.2, 100)
    k_theo_smooth = [theoretical_degree(num_rings_log, c, density, d, delta_log) for d in d0_smooth]

    plt.loglog(d0_smooth, k_theo_smooth, color='purple', linewidth=2, label='Theory (Bessel)')
    plt.loglog(d0_array, k_exp_log, marker='D', linestyle='', color='limegreen', markeredgecolor='black',
               label='Experiment')

    # Reference asymptotes (Slopes 1 and 2)
    plt.loglog(d0_smooth, theoretical_degree(num_rings_log, c, density, 0.005, delta_log) *
               (d0_smooth / 0.005) ** 1,
               'k:', alpha=0.5, label='Slope 1 (1D)')
    plt.loglog(d0_smooth, theoretical_degree(num_rings_log, c, density, 0.3, delta_log) *
               (d0_smooth / 0.3) ** 2, 'k--',
               alpha=0.5, label='Slope 2 (2D)')

    # Crossover visual marker
    plt.axvline(delta_log, color='orange', linestyle='-.', label=r'Physical Equality ($d_0 = \Delta$)')
    plt.title(r"Dimensional Crossover: Experimental vs Theory", fontsize=15)
    plt.xlabel(r"Decay Length $d_0$ (Log Scale)", fontsize=13)
    plt.ylabel(r"Average Degree $\langle k \rangle$ (Log Scale)", fontsize=13)
    plt.grid(True, which="both", alpha=0.3)
    plt.legend()
    plt.savefig(os.path.join(dir_name, "plot_2_loglog.png"), dpi=400)
    print("  -> plot_2_loglog.png saved successfully.")
    plt.close()
else:
    print("  -> Skipped Plot 2 (User opted out).")

print("\n" + "=" * 60)
print(f"   VALIDATION SUITE COMPLETED SUCCESSFULLY")
print(f"   Check the '{dir_name}' folder.")
print("=" * 60 + "\n")