import glob
import json
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib.lines import Line2D
from matplotlib.ticker import MaxNLocator

# =============================================================================
# TRIADIC PERCOLATION: LOCAL ANALYSIS SUITE
# =============================================================================
# This script is designed to process, aggregate, and visualize the data generated by the Proteus simulation engines.
# Since heavy simulations are intended to run on HPC clusters, this suite runs locally to extract metrics from the
# generated JSON files and NumPy arrays, effectively separating the computation phase from the visualization phase.

# It performs both local plotting (using a representative single seed for structural and spatiotemporal visualizations)
# and global statistical analysis (performing ensemble averages and calculating error bars across multiple seeds). When
# talking about 3 clusters in the graphs description, it means if the user inputs to do it, if not, there will be only
# 2 clusters on those plots.

# The selected parameters by the user will be referenced as the targeted set of parameters. It includes: N, Tmax, c,
# cpos, cneg, d0, dr, num_rings, and RC_factor.

# --- PLOTTING CATEGORIES & EXPECTED OUTPUTS ---

# - GLOBAL (APPLIES TO 1D, 2D, AND SCALABLE):
#     - Average Shortest Path (Hops) vs Control Parameter (p): the 'y' value is calculated getting a sample of nodes
#       and measure the shortest path of each node in that sample with ALL the other nodes in the sample. This is made
#       for each seed in a simulation with the targeted set of parameters, computing the mean of all those values. If
#       there are 5 seeds, there will be 5 means for EACH value of p. Then average those 5 means to get the final
#       point for that p in the global plot, and the error bars are the standard deviation of those 5 means. This is
#       done for each value of p, for t=0 and t=Tmax so if there are 10 values of p, there will be 10 values for t=0
#       and 10 for t=Tmax. This graph has two lines:
#         - Structural baseline (t=0): horizontal, it's a mean of those 10 values for t=0 (just for reference)
#         - Steady state (t=Tmax): plot of those 10 'average shortest path' values vs the corresponding p values, with
#           error bars.
#     - Average Fraction of Active Nodes (R) vs Control Parameter (p): similar to the previous one but instead of
#       'average shortest path' it calculates the average fraction of active nodes (R) along the time for each seed
#       and then average across seeds for each p. This graph has one line for each set of the parameters [c, cpos,
#       cneg, d0, dr] (except p, and with the same N) used on the simulations, so if there are 3 different sets of
#       parameters, there will be 3 lines in the graph, each with its own color and error bars.
#     - Fraction of Active Nodes (R) vs Time (iterations): for each p, it calculates the average of R across seeds at
#       each time step (after the transient time TT), so if there are 10 values of p, there will be 10 lines in the
#       graph, each with its own color and shaded error bars (std across seeds). This is made for all the simulations
#       with the targeted set of parameters.
#     - Fraction of Active Nodes (R) vs Control Parameter (p) - Violin plot: it takes all the simulations with
#       the targeted set of parameters, and for each p it takes all the R values across seeds and time steps (after
#       the transient time TT) and plots a violin plot of those R values vs p. So if there are 10 values of p, there
#       will be 10 violins in the graph, each with its own color.

# - 1D (RING GEOMETRY) - LOCAL SIMULATION PLOTS:
#     - Fraction of Active Nodes (R) vs Time (iterations): it averages R across seeds at each time step (after the
#       transient time TT) and plots it vs time. It can generate a global graph with the 3 bigger clusters or 3 graphs,
#       one per cluster, each with its own color and shaded error bars (std across seeds).
#     - Physical Link Length Distribution: histogram with the link lengths, with the theoretical exponential decay
#       curve overlaid for comparison. This pure exponential shape occurs because in a 1D geometry, the available
#       space to find neighbors remains constant regardless of distance, allowing the fundamental connectivity rule
#       to dictate the distribution without geometrical interference. This is made using the data from all seeds,
#       so if there are 5 seeds, there will be one histogram with the link lengths of all those 5 seeds together,
#       and the exponential decay curve overlaid.
#     - Regulatory In-Degree Distribution (kappa_in): histogram displaying the number of regulatory nodes that exert
#       influence over each structural link, separated by positive and negative regulations. Physically, since the
#       "targets" being searched in the space are nodes, this distribution is governed purely by the spatial density
#       of nodes and the regulatory connectivity kernel, unlike kappa_out which depends on the topology's link
#       density. This is made using the data from all seeds, so if there are 5 seeds, there will be one single
#       aggregated histogram pooling all their data together to form a smooth statistical distribution, with
#       the theoretical mean from the analytical model marked as a vertical line.
#     - Regulatory Out-Degree Distribution (kappa_out): histogram displaying the number of structural links regulated
#       by each individual node, separated by positive and negative regulations. Physically, since the "targets" being
#       searched in the space are the structural links (their midpoints), this distribution is strongly governed by
#       the underlying topology's link density and the regulatory connectivity kernel, unlike kappa_in which depends
#       only on node density. This is made using the data from all seeds, so if there are 5 seeds, there will be one
#       single aggregated histogram pooling all their data together to form a smooth statistical distribution, with
#       the theoretical mean from the analytical model marked as a vertical line.
#     - Structural Degree Distribution (k): histogram displaying the total number of physical connections (edges) each
#       node has within the structural network. Physically, the formation of these links is governed by the structural
#       connectivity kernel (exponential decay with distance d0). However, since a node's total degree is the
#       macroscopic sum of N-1 independent distance-weighted Bernoulli trials across the space, the Central Limit
#       Theorem dictates that this distribution will naturally form a symmetric Gaussian (Normal) bell curve around
#       its expected value. This is made using the data from all seeds, so if there are 5 seeds, there will be one
#       single aggregated histogram pooling all their data together to form a smooth statistical distribution,
#       with the theoretical mean from the analytical model marked as a vertical line.
#     - Topological Distance Shift (Hops): histograms comparing the shortest path lengths at t=0 (intact structural
#       network) and t=Tmax (surviving active component). The distribution at t=0 reflects the underlying structural
#       topology, while the distribution at t=Tmax reveals how the dynamics have pruned the network and altered its
#       effective topology. This is made using the data from all seeds, so if there are 5 seeds, there will be three
#       histograms (one for t=0, one for t=Tmax and one comparing both) with the shortest path lengths of all those 5
#       seeds together, and the mean of each distribution marked as a vertical line.
#     - Phase Space: Size vs Angular Position: this graph shows 3 variables: the fraction of active nodes (R) on the
#       'y' axis, the average angular position of the cluster within the ring (rad) on the 'x' axis, and the time as
#       a color gradient. The average angular position is calculated as the circular mean of the positions of the
#       active nodes in the ring, weighted by their degree. This graph can reveal interesting dynamical trajectories.
#     - Spatial Position over Time: graph displaying the average angular position of the cluster (rad) on the 'y'
#       axis and the time (iterations) on the 'x' axis.
#     - Spatio-temporal Evolution: raster plot displaying the spatial position of the active nodes over time. The 'y'
#       axis represents the position of the nodes in the ring represented as a single line with height y=L and PBC,
#       while the 'x' axis represents time (iterations). Each point in the plot indicates when a node is active.
#     - Topological vs Geometric Distance: graph displaying the topological distance (number of hops) on the 'y' axis
#       and the geometric distance (physical space) on the 'x' axis. The scatter plot represents thousands of node pairs
#       as individual points, capturing the high variance of path efficiencies (the Small-World effect).
#     - Spatial Width over Time: graph displaying the spatial spread or angular standard deviation of the cluster
#       (rad) on the 'y' axis and the time (iterations) on the 'x' axis.

# - 2D (TOROIDAL GEOMETRY) - LOCAL SIMULATION PLOTS:
#     - Fraction of Active Nodes (R) vs Time (iterations): Same as 1D.
#     - Physical Link Length Distribution: histogram with the link lengths, with the theoretical geometric-exponential
#       decay curve overlaid for comparison. Unlike the pure exponential in 1D, the 2D theoretical curve follows
#       P(d) ~ d * exp(-d/d0). This asymmetric, mountain-like shape occurs because the available space (the perimeter
#       of a search circle) grows linearly with distance.
#     - Regulatory In-Degree Distribution (kappa_in): Same underlying physical principles as 1D, mapped to 2D.
#     - Regulatory Out-Degree Distribution (kappa_out): Same underlying physical principles as 1D, mapped to 2D.
#     - Structural Degree Distribution (k): Symmetric Gaussian bell curve.
#     - Topological Distance Shift (Hops): Same as 1D.
#     - 2D Spatial Activity Heatmap: scatter plot representing the physical embedding of the network in the 2D toroidal
#       space (X and Y coordinates). The color of each node (using a thermal gradient) represents its overall activation
#       frequency across the entire simulation time (Tmax). This visualization reveals spatial patterns, such as whether
#       activity is globally homogenous or localized into specific persistent pockets/clusters. This is made for a
#       single representative seed.
#     - Topological vs Geometric Distance: Same as 1D, but using 2D Euclidean distances with PBC.

# - SCALABLE (COUPLED RINGS) - LOCAL SIMULATION PLOTS:
#     - Fraction of Active Nodes (R) vs Time (iterations): Same as 1D and 2D.
#     - Physical Link Length Distribution: histogram with the link lengths, with the theoretical 2D
#       geometric-exponential decay curve overlaid. The empirical distribution captures the hybrid nature of the
#       geometry (continuous in X, discrete in Y), converging toward the continuous 2D theory as the number of rings
#       (Nr) increases.
#     - Regulatory In-Degree & Out-Degree Distributions: Same physical principles, calculated over the coupled rings
#       topology using the independently calibrated regulatory decay lengths (dr) for each specific resolution (Nr).
#     - Structural Degree Distribution (k): Symmetric Gaussian bell curve. The theoretical mean is derived from the
#       Bessel-function based integration specific to the refinement model geometry.
#     - Topological Distance Shift (Hops): Same as 1D and 2D.
#     - 2D Spatial Activity Heatmap: scatter plot representing the physical embedding of the network in the universe
#       (X as continuous horizontal position, Y as discrete vertical rings). The color of each node represents its
#       overall activation frequency across Tmax. This visualization reveals spatial clustering and transversal
#       connections.
#     - Topological vs Geometric Distance: scatter plot displaying the topological distance against the 2D physical
#       distance (Pythagorean distance with double PBC). Captures the Small-World effect across the coupled rings.

# - CROSS-DIMENSIONAL (MASTER PLOTS) - PERCOLATION & TRANSITION:
#     - Dimensional Shift of the Triadic Percolation Transition (R vs p): Master graph displaying the fraction of
#       active nodes (R) against the control parameter (p). It overlaps the 1D limit, 2D limit, and the intermediate
#       coupled rings resolutions (Nr) to visually demonstrate how the transition point shifts as dimensions increase.
#     - Thermodynamic Susceptibility (\chi) vs Control Parameter (p): Graph displaying the susceptibility
#       (calculated as N * \sigma_R^2) against p. It reveals the exact critical point (p_c) of the phase transition
#       through a divergence peak, demonstrating the explosive nature of triadic percolation.
#     - Critical Parameter (p_c) vs Dimensionality (Nr): Graph tracking the exact location of the susceptibility peak
#       (p_c) as a function of the system's resolution (Number of Rings). It features the 1D and 2D limits as infinite
#       horizontal asymptotes, visually proving the continuous dimensional crossover of the network's robustness.
#
# =============================================================================

# =============================================================================
# GLOBAL ANALYSIS SETUP
# =============================================================================
print("=" * 60)
print(" GLOBAL ANALYSIS SETUP")
print("=" * 60)
print("Define the baseline parameters for the Global Plots.")
print("(Press Enter on any parameter to use the default value shown in brackets)")

try:
    # Transient time (iterations to ignore for steady-state calculations)
    TT = int(input("Transient time (iterations to ignore for steady-state calculations) [5]: ") or 5)

    # Get target 'p' values for local plotting
    p_input = input("Target 'p' values for local plots (comma separated) [0.0, 0.2, 0.5, 0.8, 1.0]: ")
    if p_input.strip():
        target_p_local = [float(x.strip()) for x in p_input.split(',')]
    else:
        target_p_local = [0.0, 0.2, 0.5, 0.8, 1.0]

    # Create a multi-line plot comparing different structural/regulatory parameters?
    do_param_comparison = input("Create multi-line plots comparing different parameter sets? (y/n) "
                                "[n]: ").lower() == "y"

    plot_third_cluster = input("Plot the 3rd biggest cluster in the common graphs? (y/n) [n]: ").lower() == "y"

    print("\n" + "-" * 45)
    print(" 1D SIMULATION TARGETS")
    print("-" * 45)
    t_Tmax_1d = int(input("Target Tmax [400]: ") or 400)
    t_N_1d    = int(input("Target N for plots 1, 2, 3 and 4 [10000]: ") or 10000)
    t_c_1d    = float(input("Target c [0.07]: ") or 0.07)
    t_cpos_1d = float(input("Target cpos [0.03]: ") or 0.03)
    t_cneg_1d = float(input("Target cneg [0.03]: ") or 0.03)
    t_d0_1d   = float(input("Target d0 [0.2]: ") or 0.2)
    t_dr_1d   = float(input("Target dr [0.2]: ") or 0.2)

    print("\n" + "-" * 45)
    print(" 2D SIMULATION TARGETS")
    print("-" * 45)
    t_Tmax_2d = int(input("Target Tmax [1000]: ") or 1000)
    t_N_2d    = int(input("Target N for plots 1, 2, 3 and 4 [10000]: ") or 10000)
    t_c_2d    = float(input("Target c [0.4]: ") or 0.4)
    t_cpos_2d = float(input("Target cpos [0.2]: ") or 0.2)
    t_cneg_2d = float(input("Target cneg [0.2]: ") or 0.2)
    t_d0_2d   = float(input("Target d0 [0.25]: ") or 0.25)
    t_dr_2d   = float(input("Target dr [0.25]: ") or 0.25)
    t_RC_2d = float(input("Target RC factor (Lx/Ly) [1.0]: ") or 1.0)

    print("\n" + "-" * 45)
    print(" RINGS SIMULATION TARGETS")
    print("-" * 45)
    t_Tmax_rings = int(input("Target Tmax [500]: ") or 500)
    t_N_rings = int(input("Target N for plots 1, 2, 3 and 4 [10000]: ") or 10000)
    t_c_rings = float(input("Target c [0.07]: ") or 0.07)
    t_cpos_rings = float(input("Target cpos [0.03]: ") or 0.03)
    t_cneg_rings = float(input("Target cneg [0.03]: ") or 0.03)

    # Allow multiple target rings for local plotting (comma separated)
    rings_input = input("Target num_rings (for local plots, comma separated) [1, 2, 5, 15, 35, 60]: ")
    if rings_input.strip():
        t_num_rings = [int(x.strip()) for x in rings_input.split(',')]
    else:
        t_num_rings = [1, 2, 5, 15, 35, 60]

    print("\n  -> Master Plot Asymptotic Limits:")
    t_limit_d0_1d = float(input("     Target 1D d0/dr limit [0.2]: ") or 0.2)
    t_limit_d0_2d = float(input("     Target 2D d0/dr limit [1.787]: ") or 1.787)

except ValueError:
    print("Invalid input! Exiting setup. Please use numeric values.")
    exit()

# =============================================================================
# CONFIGURATION AND IMPORTANT LISTS/MAPS
# =============================================================================
# Lists for the 1D global plots
global_R_vs_p_1D = []
global_R_time_series_1D = []
all_R_fluctuations_1D = []
steady_state_distances_1D = []

# Lists for the 2D global plots
global_R_vs_p_2D = []
global_R_time_series_2D = []
all_R_fluctuations_2D = []
steady_state_distances_2D = []

# Lists for the RINGS global plots
global_R_vs_p_RINGS = []
global_R_time_series_RINGS = []
all_R_fluctuations_RINGS = []
steady_state_distances_RINGS = []

# Independent lists strictly for the Master Plots Asymptotic limits
master_limit_1D = []
master_limit_2D = []

# Define the new base directories
base_dirs = {
    "1D": "./results/1D/",
    "2D": "./results/2D/",
    "RINGS": "./results/scalable/"
}

param_folders = []

# Scan the three base directories
for dim_label, b_dir in base_dirs.items():
    if os.path.exists(b_dir):
        for p_folder in os.listdir(b_dir):
            p_path = os.path.join(b_dir, p_folder)

            # Check if it's a directory and NOT a global analysis folder
            if os.path.isdir(p_path) and "global" not in p_folder:
                # Find all seed folders inside this parameter configuration
                seed_dirs = [d for d in os.listdir(p_path) if d.startswith("seed=")]
                if len(seed_dirs) > 0:
                    param_folders.append({
                        "dim": dim_label,
                        "path": p_path,
                        "seeds": sorted(seed_dirs)
                    })

if not param_folders:
    print("No parameter folders with seeds found in 1D, 2D, or scalable directories.")
    exit()

# Sort alphabetically by path for consistent output
param_folders = sorted(param_folders, key=lambda x: x["path"])

# Count how many are 1D, RINGS, and 2D based on folder names or internal logic
count_1d = sum(1 for f in param_folders if f["dim"] == "1D")
count_rings = sum(1 for f in param_folders if f["dim"] == "RINGS")
count_2d = sum(1 for f in param_folders if f["dim"] == "2D")

print("=" * 60)
print(f"Found {len(param_folders)} simulation folders in total:")
print(f"  -> 1D Simulations (Ring)     : {count_1d}")
print(f"  -> Coupled Rings (Discrete)  : {count_rings}")
print(f"  -> 2D Simulations (Toroidal) : {count_2d}")

# =============================================================================
# INDIVIDUAL FOLDER ANALYSIS LOOP
# =============================================================================
for p_data in param_folders:
    folder = p_data["path"]
    current_dim_label = p_data["dim"]
    seed_list = p_data["seeds"]

    print("=" * 60)
    print(f"Processing Parameter Set: {os.path.basename(folder)}")
    print(f"-> Averaging {len(seed_list)} seeds...")

    # Create figure directory inside the parameter folder
    fig_dir = os.path.join(folder, "figures")

    # ---------------------------------------------------------
    # 1. LOAD REPRESENTATIVE DATA (From the first seed)
    # ---------------------------------------------------------
    # We use the first seed for target matching
    first_seed_path = os.path.join(folder, seed_list[0])
    json_path = os.path.join(first_seed_path, "summary_metrics.json")

    if not os.path.exists(json_path):
        print(f"-> Missing JSON in first seed {first_seed_path}. Skipping...")
        continue

    with open(json_path, 'r') as f:
        data = json.load(f)

    # Extract parameters of the simulation for this iteration
    p = data["parameters"]["p"]
    N = data["parameters"]["N"]
    Tmax = data["parameters"]["Tmax"]
    d0 = data["parameters"]["d0"]
    dr = data["parameters"]["dr"]
    c = data["parameters"]["c"]
    cpos = data["parameters"]["cpos"]
    cneg = data["parameters"]["cneg"]

    Lx, Ly, L = 0, 0, 0

    # --- DIMENSION DETECTION & TARGET ROUTING ---
    if current_dim_label == "RINGS":
        dim = "RINGS"
        # Extract RINGS specific parameters from the JSON summary
        num_rings_val = data["parameters"].get("num_rings", 1)
        Lx = data["parameters"].get("Lx", 0)
        Ly = data["parameters"].get("Ly", 0)

        # Target matching for global plots (Cross-Dimensional and R vs p)
        target_Tmax, target_N = t_Tmax_rings, t_N_rings
        target_c, target_cpos, target_cneg = t_c_rings, t_cpos_rings, t_cneg_rings
        # Note: we don't match d0/dr here because they are calibrated for each Nr

        match_topology = (round(c, 3) == round(target_c, 3) and
                          round(cpos, 3) == round(target_cpos, 3) and
                          round(cneg, 3) == round(target_cneg, 3) and
                          Tmax == target_Tmax and
                          N == target_N and
                          num_rings_val in t_num_rings)

    elif current_dim_label == "2D":
        dim = 2
        RC_factor = data["parameters"].get("RC_factor", 1.0)
        L_list = data["parameters"].get("L", [0, 0])
        Lx, Ly = L_list[0], L_list[1]

        # Load the 2D targets the user inputted
        target_Tmax, target_N = t_Tmax_2d, t_N_2d
        target_c, target_cpos, target_cneg = t_c_2d, t_cpos_2d, t_cneg_2d
        target_d0, target_dr = t_d0_2d, t_dr_2d
        target_RC = t_RC_2d

        match_topology = (round(c, 3) == round(target_c, 3) and
                          round(cpos, 3) == round(target_cpos, 3) and
                          round(cneg, 3) == round(target_cneg, 3) and
                          round(d0, 3) == round(target_d0, 3) and
                          round(dr, 3) == round(target_dr, 3) and
                          Tmax == target_Tmax and
                          round(RC_factor, 2) == round(target_RC, 2))
    else:
        dim = 1
        RC_factor = 1.0
        # In 1D, L is just a float
        L = data["parameters"]["L"]

        # Load the 1D targets the user inputted
        target_Tmax, target_N = t_Tmax_1d, t_N_1d
        target_c, target_cpos, target_cneg = t_c_1d, t_cpos_1d, t_cneg_1d
        target_d0, target_dr = t_d0_1d, t_dr_1d
        target_RC = 1.0

        match_topology = (round(c, 3) == round(target_c, 3) and
                          round(cpos, 3) == round(target_cpos, 3) and
                          round(cneg, 3) == round(target_cneg, 3) and
                          round(d0, 3) == round(target_d0, 3) and
                          round(dr, 3) == round(target_dr, 3) and
                          Tmax == target_Tmax)

    # ---------------------------------------------------------
    # 2. EXTRACT STEADY-STATE METRICS ACROSS SEEDS
    # ---------------------------------------------------------
    # Degrees metrics
    k_exp_arr = {
        "structural": [],
        "out_pos": [],
        "out_neg": [],
        "in_pos": [],
        "in_neg": []
    }

    # Theoretical values are the same across seeds for the same parameters, so we only need to load them once
    k_theo = {
        "structural": data["degrees_summary"]["k_theo"],
        "out_pos": data["degrees_summary"]["kappa_out_pos_theo"],
        "out_neg": data["degrees_summary"]["kappa_out_neg_theo"],
        "in_pos": data["degrees_summary"]["kappa_in_pos_theo"],
        "in_neg": data["degrees_summary"]["kappa_in_neg_theo"]
    }

    # Topological metrics (distances and hops)
    path_length_hops = {
        "t0": [],
        "tmax": []
    }

    links_length_distance = []

    topological_distances = []
    geometric_distances = []

    # Lists to temporarily store the mean distances of each seed for global error calculation
    seed_mean_distances_t0 = []
    seed_mean_distances_tmax = []

    # Time series
    RT_mean_time_series = np.array([])
    RT_std_time_series = np.array([])
    all_RT_matrices = []
    seed_RT_dict = {}
    state_nodes_dict = {}
    nodes_coords_dict = {}  # This is not time series, but is related with state_nodes_dict

    # Angles metrics (one for each seed)
    seed_angular_data = {}

    for seed_name in seed_list:
        print(f"    --> Extracting raw data from {seed_name}...")
        seed_path = os.path.join(folder, seed_name)

        # SUMMARY_METRICS
        try:
            # Load JSON data for this seed to extract the metrics
            with open(os.path.join(seed_path, "summary_metrics.json"), 'r') as sf:
                s_data = json.load(sf)

            # Add all the degree values to the corresponding global lists for the histograms
                # Use np.ravel() to guarantee 1D arrays, as sparse matrices in RINGS save them as 2D lists [[x], [y]]
                k_exp_arr["structural"].extend(np.ravel(s_data["degrees_arrays"]["k_real_array"]))
                k_exp_arr["out_pos"].extend(np.ravel(s_data["degrees_arrays"]["kappa_out_pos_array"]))
                k_exp_arr["out_neg"].extend(np.ravel(s_data["degrees_arrays"]["kappa_out_neg_array"]))
                k_exp_arr["in_pos"].extend(np.ravel(s_data["degrees_arrays"]["kappa_in_pos_array"]))
                k_exp_arr["in_neg"].extend(np.ravel(s_data["degrees_arrays"]["kappa_in_neg_array"]))

            # Add seed-level mean distances to calculate the ensemble standard deviation later
            seed_mean_distances_t0.append(s_data["distances"]["mean_hops_t0"])
            seed_mean_distances_tmax.append(s_data["distances"]["mean_hops_tfinal"])

        except FileNotFoundError:
            print(f"-> Missing summary_metrics.json for {seed_name}.")
            continue

        # TOPOLOGY DATA
        try:
            # Load npz data for this seed to extract the metrics
            topo_data = np.load(os.path.join(seed_path, "topology_data.npz"))

            # Add all the path lengths to the corresponding global lists for the histograms
            path_length_hops["t0"].extend(topo_data["path_lengths_t0"])
            path_length_hops["tmax"].extend(topo_data["path_lengths_tfinal"])

            # Add all the link lengths to the corresponding global list for the histogram
            links_length_distance.extend(topo_data["link_lengths"])

            # Add all the topological and geometric distances to the corresponding global lists for the scatter plot
            topological_distances.extend(topo_data['topo_distances'])
            geometric_distances.extend(topo_data['geom_distances'])

        except FileNotFoundError:
            print(f"-> Missing topology_data.npz for {seed_name}.")

        # FRACTION OF ACTIVE NODES DATA
        try:
            # Load dynamic arrays
            RT = np.loadtxt(os.path.join(seed_path, "RT.txt"))

            # The structure of this RT is [time_steps, num_clusters], where num_clusters includes the giant component as
            # the first column (index 0)
            all_RT_matrices.append(RT)

            # Map this time serie
            seed_RT_dict[seed_name] = RT

        except FileNotFoundError:
            print(f"-> Missing RT.txt for {seed_name}.")

        # NODES STATES DATA
        try:
            # Load nodes states and spatial compressed data (for raster plots)
            state_nodes = np.load(os.path.join(seed_path, "statenodes.npz"))['statenodes']
            nodes_coords = np.load(os.path.join(seed_path, "nodes_coords.npy"))

            state_nodes_dict[seed_name] = state_nodes
            nodes_coords_dict[seed_name] = nodes_coords

        except FileNotFoundError:
            print(f"-> Missing nodes states data for {seed_name}.")
            pass

        # ANGULAR METRICS
        try:
            spatial_dyn = np.loadtxt(os.path.join(seed_path, "spatial_dyn.txt"))

            # The [:, 0::2] slicing takes columns 0, 2, 4 (Positions)
            # The [:, 1::2] slicing takes columns 1, 3, 5 (Widths)
            seed_angular_data[seed_name] = {
                "angular_positions": spatial_dyn[:, 0::2],
                "angular_widths": spatial_dyn[:, 1::2]
            }

        except FileNotFoundError:
            print(f"-> Missing spatial_dyn.txt for {seed_name}.")
            pass

    # Averaging the R from all the seeds so the useful array is [steady_time_steps, num_clusters] and getting the
    # standard deviation across seeds
    if len(all_RT_matrices) > 0:
        # Convert the list of matrices into a 3D tensor: shape = (num_seeds, Tmax, num_clusters)
        RT_tensor = np.array(all_RT_matrices)

        # Calculate the mean and standard deviation across the seed axis (axis=0)
        # Resulting shapes will be (Tmax, num_clusters)
        RT_mean_time_series = np.mean(RT_tensor, axis=0)
        RT_std_time_series = np.std(RT_tensor, axis=0)

        # ---------------------------------------------------------
        # GLOBAL PLOTS DATA COLLECTION
        # ---------------------------------------------------------
        if match_topology and N == target_N:
            # 1. TIME SERIES
            time_arr = np.arange(len(RT_mean_time_series[:, 0]))
            mean_r_arr = RT_mean_time_series[:, 0]
            std_r_arr = RT_std_time_series[:, 0]

            ts_dict = {'p': p, 'time': time_arr, 'R': mean_r_arr, 'R_std': std_r_arr,
                       'num_rings': num_rings_val if dim == "RINGS" else None}

            # 2. VIOLIN PLOT FLUCTUATIONS
            # This takes all the seeds value of the giant component and concatenates them into a single array, but only
            # after the transient time TT, so it is the steady state fluctuations of R across seeds for this parameter
            # configuration. This is used for the violin plot of R fluctuations across p.
            raw_fluctuations = RT_tensor[:, TT:, 0].flatten()

            fluct_data = [{'p': p, 'R': r_val, 'num_rings': num_rings_val if dim == "RINGS" else None}
                          for r_val in raw_fluctuations]

            if dim == 1:
                global_R_time_series_1D.append(ts_dict)
                all_R_fluctuations_1D.extend(fluct_data)
            elif dim == "RINGS":
                global_R_time_series_RINGS.append(ts_dict)
                all_R_fluctuations_RINGS.extend(fluct_data)
            elif dim == 2:
                global_R_time_series_2D.append(ts_dict)
                all_R_fluctuations_2D.extend(fluct_data)

            # 3. TOPOLOGICAL DISTANCES (Mean and Std across seeds)
            if len(seed_mean_distances_t0) > 0 and len(seed_mean_distances_tmax) > 0:
                # Calculate the ensemble average
                mean_dist_t0 = np.mean(seed_mean_distances_t0)
                mean_dist_tmax = np.mean(seed_mean_distances_tmax)

                # Calculate the standard deviation across seeds (ddof=1 for sample standard deviation)
                std_dist_tmax = np.std(seed_mean_distances_tmax, ddof=1)

                dist_dict = {
                    'p': p,
                    'dist_t0': mean_dist_t0,
                    'dist_tmax': mean_dist_tmax,
                    'dist_tmax_std': std_dist_tmax,
                    'num_rings': num_rings_val if dim == "RINGS" else None
                }

                if dim == 1:
                    steady_state_distances_1D.append(dist_dict)
                elif dim == "RINGS":
                    steady_state_distances_RINGS.append(dist_dict)
                elif dim == 2:
                    steady_state_distances_2D.append(dist_dict)

        # 4. VARYING PARAMETERS R VS P
        if Tmax == target_Tmax and N == target_N:
            steady_tensor = RT_tensor[:, TT:, 0]

            # R_mean total
            r_mean_total = np.mean(steady_tensor)

            # The R_std ois calculated from the mean of each seed
            seed_steady_means = np.mean(steady_tensor, axis=1)
            r_std_total = np.std(seed_steady_means, ddof=1)

            # THERMODYNAMIC SUSCEPTIBILITY (chi)
            # chi = N * ( <R^2> - <R>^2 ). It measures the fluctuations of the giant component size
            # across different universes (seeds). It will peak exactly at the critical point p_c.
            susceptibility = N * (r_std_total ** 2)

            r_vs_p_dict = {
                'p': p,
                'R_mean': r_mean_total,
                'R_std': r_std_total,
                'susceptibility': susceptibility,
                'c': c, 'cpos': cpos, 'cneg': cneg, 'd0': d0, 'dr': dr,
                'Tmax': Tmax,
                'num_rings': num_rings_val if dim == "RINGS" else None
            }

            if dim == 1:
                global_R_vs_p_1D.append(r_vs_p_dict)
            elif dim == "RINGS":
                global_R_vs_p_RINGS.append(r_vs_p_dict)
            elif dim == 2:
                global_R_vs_p_2D.append(r_vs_p_dict)

        # 5. ASYMPTOTIC LIMITS EXTRACTION (For Master Plots)
        # Explicitly isolates the specific 1D and 2D runs intended as boundaries for the RINGS model.
        is_1D_limit = (dim == 1 and Tmax == t_Tmax_rings and N == t_N_rings and
                       round(d0, 3) == round(t_limit_d0_1d, 3) and round(dr, 3) == round(t_limit_d0_1d, 3) and
                       round(c, 3) == round(t_c_rings, 3) and round(cpos, 3) == round(t_cpos_rings,3) and
                       round(cneg,3) == round(t_cneg_rings, 3))

        is_2D_limit = (dim == 2 and Tmax == t_Tmax_rings and N == t_N_rings and
                       round(d0, 3) == round(t_limit_d0_2d, 3) and round(dr, 3) == round(t_limit_d0_2d, 3) and
                       round(c, 3) == round(t_c_rings, 3) and round(cpos, 3) == round(t_cpos_rings,3) and
                       round(cneg, 3) == round(t_cneg_rings, 3))

        if is_1D_limit or is_2D_limit:
            steady_tensor_lim = RT_tensor[:, TT:, 0]
            r_mean_lim = np.mean(steady_tensor_lim)
            seed_steady_means_lim = np.mean(steady_tensor_lim, axis=1)
            r_std_lim = np.std(seed_steady_means_lim, ddof=1)
            susceptibility_lim = N * (r_std_lim ** 2)

            lim_dict = {
                'p': p, 'R_mean': r_mean_lim, 'R_std': r_std_lim, 'susceptibility': susceptibility_lim,
                'num_rings': None
            }

            if is_1D_limit: master_limit_1D.append(lim_dict)
            if is_2D_limit: master_limit_2D.append(lim_dict)

    # ---------------------------------------------------------
    # CONDITION FOR GENERATING LOCAL PLOTS (TIME SAVER)
    # Only draw if it matches the target topology and 'p' is in the favorite list.
    # Use np.isclose to avoid floating point precision issues (e.g., 0.2000001 != 0.2)
    # ---------------------------------------------------------
    make_local_plots = match_topology and any(np.isclose(p, target_p, atol=1e-3) for target_p in target_p_local)

    if make_local_plots:
        os.makedirs(fig_dir, exist_ok=True)
        # ---------------------------------------------------------
        # 3. DEGREE DISTRIBUTION HISTOGRAMS
        # ---------------------------------------------------------
        print("-> Generating Degree Distributions...")
        # Structural Degree (physically connected nodes)
        plt.figure(figsize=(6, 4))
        sns.histplot(np.ravel(k_exp_arr['structural']), discrete=True, color='skyblue', stat='probability', alpha=0.8)
        plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
        plt.axvline(k_theo['structural'], color='red', linestyle='--', linewidth=2,
                    label=f"Theo Mean: {k_theo['structural']:.2f}")
        plt.title("Structural Degree Distribution P(k)")
        plt.xlabel("Degree k (Connections per node)")
        plt.ylabel("Probability")
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(fig_dir, f"hist_structural_degree_p{p:.2f}.png"), dpi=400)
        plt.close()

        # Regulatory Out-Degree (nodes regulating links)
        plt.figure(figsize=(6, 4))
        sns.histplot(np.ravel(k_exp_arr['out_pos']), discrete=True, color='green', alpha=0.5, stat='probability',
                     label='Positive (+)')
        sns.histplot(np.ravel(k_exp_arr['out_neg']), discrete=True, color='red', alpha=0.5, stat='probability',
                     label='Negative (-)')
        plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
        plt.axvline(k_theo['out_pos'], color='darkgreen', linestyle='--', linewidth=2, label='Theo. Mean (+)')
        plt.axvline(k_theo['out_neg'], color='darkred', linestyle='--', linewidth=2, label='Theo. Mean (-)')
        plt.title("Regulatory Out-Degree Distribution P(k_out)")
        plt.xlabel("Out-Degree (Nodes regulating links)")
        plt.ylabel("Probability")
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(fig_dir, f"hist_regulatory_out_degree_p{p:.2f}.png"), dpi=400)
        plt.close()

        # Regulatory In-Degree (links regulated by nodes)
        plt.figure(figsize=(6, 4))
        sns.histplot(np.ravel(k_exp_arr['in_pos']), discrete=True, color='green', alpha=0.5, stat='probability',
                     label='Positive (+)')
        sns.histplot(np.ravel(k_exp_arr['in_neg']), discrete=True, color='red', alpha=0.5, stat='probability',
                     label='Negative (-)')
        plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
        plt.axvline(k_theo['in_pos'], color='darkgreen', linestyle='--', linewidth=2, label='Theo. Mean (+)')
        plt.axvline(k_theo['in_neg'], color='darkred', linestyle='--', linewidth=2, label='Theo. Mean (-)')
        plt.title("Regulatory In-Degree Distribution P(k_in)")
        plt.xlabel("In-Degree (Links regulated by nodes)")
        plt.ylabel("Probability")
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(fig_dir, f"hist_regulatory_in_degree_p{p:.2f}.png"), dpi=400)
        plt.close()

        # ---------------------------------------------------------
        # 4. TOPOLOGY & DISTANCE PLOTS
        # ---------------------------------------------------------
        print("-> Generating Topology Plots...")

        # Conditionals
        t0_plot = len(path_length_hops["t0"]) > 0
        tmax_plot = len(path_length_hops["tmax"]) > 0
        links_length_plot = len(links_length_distance) > 0
        topo_vs_geom_plot = len(topological_distances) > 0 and len(geometric_distances) > 0

        # Means for the vertical lines
        mean_hops_t0 = np.mean(path_length_hops["t0"]) if t0_plot else 0
        mean_hops_tmax = np.mean(path_length_hops["tmax"]) if tmax_plot else 0

        # A.1. Topological Distance Histogram (t=0)
        if t0_plot:
            plt.figure(figsize=(6, 4))
            sns.histplot(path_length_hops["t0"], discrete=True, color='mediumpurple',
                         edgecolor='black', alpha=0.7, stat='probability')
            plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
            plt.axvline(mean_hops_t0, color='red', linestyle='dashed', linewidth=2,
                        label=f'Mean (t=0): {mean_hops_t0:.2f}')
            plt.title("Topological Distance Distribution at t=0")
            plt.xlabel("Number of Hops (Topological Distance)")
            plt.ylabel("Probability")
            plt.legend()
            plt.tight_layout()
            plt.savefig(os.path.join(fig_dir, f"hist_topological_distances_t0_p{p:.2f}.png"), dpi=400)
            plt.close()

        # A.2. Topological Distance Histogram (t=Tmax)
        if tmax_plot:
            plt.figure(figsize=(6, 4))
            sns.histplot(path_length_hops["tmax"], discrete=True, color='darkorange',
                         edgecolor='black', alpha=0.7, stat='probability')
            plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
            plt.axvline(mean_hops_tmax, color='red', linestyle='dashed', linewidth=2,
                        label=f'Mean (t=Tmax): {mean_hops_tmax:.2f}')
            plt.title("Active Topological Distance Distribution at t=Tmax")
            plt.xlabel("Number of Hops (Topological Distance)")
            plt.ylabel("Probability")
            plt.legend()
            plt.tight_layout()
            plt.savefig(os.path.join(fig_dir, f"hist_topological_distances_tfinal_p{p:.2f}.png"), dpi=400)
            plt.close()

        # A.3. Topological Distance Histogram (Combined t=0 vs t=Tmax)
        if t0_plot and tmax_plot:
            plt.figure(figsize=(6, 4))
            # Plot both histograms with transparency
            sns.histplot(path_length_hops["t0"], discrete=True, color='mediumpurple',
                         edgecolor='black', alpha=0.5, stat='probability', label='t=0 (Structural)')
            sns.histplot(path_length_hops["tmax"], discrete=True, color='darkorange',
                         edgecolor='black', alpha=0.5, stat='probability', label='t=Tmax (Active)')
            plt.gca().xaxis.set_major_locator(MaxNLocator(integer=True))
            plt.axvline(mean_hops_t0, color='purple', linestyle='dashed', linewidth=2,
                        label=f'Mean t=0 ({mean_hops_t0:.1f})')
            plt.axvline(mean_hops_tmax, color='orangered', linestyle='dashed', linewidth=2,
                        label=f'Mean t=Tmax ({mean_hops_tmax:.1f})')

            plt.title("Topological Distance Shift (Structural vs Active)")
            plt.xlabel("Number of Hops (Topological Distance)")
            plt.ylabel("Probability")
            plt.legend()
            plt.tight_layout()
            plt.savefig(os.path.join(fig_dir, f"hist_topological_distances_combined_p{p:.2f}.png"), dpi=400)
            plt.close()

        # B. Link Length Distribution (Exponential Decay verification)
        if links_length_plot:
            plt.figure(figsize=(6, 4))
            sns.histplot(links_length_distance, bins=50, color='coral', stat='density', alpha=0.6,
                         label='Empirical Data')
            # Overlay theoretical exponential decay: P(d) ~ exp(-d/d0)
            x_vals = np.linspace(0, max(links_length_distance), 1000)
            # Overlay theoretical decay based on dimensionality
            if dim == "RINGS":
                # 1D: Pure exponential decay
                y_1d = (1 / d0) * np.exp(-x_vals / d0)
                plt.plot(x_vals, y_1d, color='purple', linewidth=2, linestyle=':',
                         label=r'1D Limit: $e^{-d/d_0}$')

                # 2D: Probability proportional to ring area (d) * exponential decay
                # As Nr increases, the discrete model converges to this continuous PDF
                y_2d = (x_vals / (d0 ** 2)) * np.exp(-x_vals / d0)
                plt.plot(x_vals, y_2d, color='red', linewidth=2, linestyle='--',
                         label=r'2D Limit: $d \cdot e^{-d/d_0}$')

                plt.title(f"Link Lengths: Dimensional Crossover (Nr={int(num_rings_val)})")
            elif dim == 1:
                # 1D: Pure exponential decay
                y_vals = (1 / d0) * np.exp(-x_vals / d0)
                plt.plot(x_vals, y_vals, color='red', linewidth=2, linestyle='--', label=r'Theory: $P(d) = '
                                                                                         r'\frac{1}{d_0} e^{-d/d_0}$')
                plt.title("Physical Link Length Distribution (1D)")
            elif dim == 2:
                # 2D: Probability proportional to ring area (d) * exponential decay
                # The normalized PDF is (x / d0^2) * exp(-x/d0)
                y_vals = (x_vals / (d0 ** 2)) * np.exp(-x_vals / d0)
                plt.plot(x_vals, y_vals, color='red', linewidth=2, linestyle='--',
                         label=r'Theory: $P(d) = \frac{d}{d_0^2} e^{-d/d_0}$')
                plt.title("Physical Link Length Distribution (2D)")

            plt.xlabel("Physical Distance (Geometry)")
            plt.ylabel("Density")
            plt.legend()
            plt.tight_layout()
            plt.savefig(os.path.join(fig_dir, f"hist_link_lengths_p{p:.2f}.png"), dpi=400)
            plt.close()

        # C. Topological vs Geometric Distance Plot
        if topo_vs_geom_plot:
            plt.figure(figsize=(6, 4))
            plt.scatter(geometric_distances, topological_distances, color='purple', alpha=0.2, s=10)

            # Calculate moving average
            geom_arr = np.array(geometric_distances)
            topo_arr = np.array(topological_distances)

            bins = np.linspace(0, np.max(geom_arr), 15)
            bin_means = []
            for i in range(len(bins) - 1):
                mask = (geom_arr >= bins[i]) & (geom_arr < bins[i + 1])
                if np.any(mask):
                    bin_means.append(np.mean(topo_arr[mask]))
                else:
                    bin_means.append(np.nan)
            bin_centers = (bins[:-1] + bins[1:]) / 2

            plt.plot(bin_centers, bin_means, color='red', linewidth=3, label='Average Trend')
            plt.title("Topological vs Geometric Distance")
            plt.xlabel("Geometric Distance (Physical Space)")
            plt.ylabel("Topological Distance (Hops)")
            plt.grid(True, linestyle='--', alpha=0.6)
            plt.legend()
            plt.tight_layout()
            plt.savefig(os.path.join(fig_dir, f"topo_vs_geom_p{p:.2f}.png"), dpi=400)
            plt.close()

        # ---------------------------------------------------------
        # 5. TIME DYNAMICS PLOTS
        # ---------------------------------------------------------
        print("-> Generating Time Dynamics Plots...")

        if RT_mean_time_series.size > 0:
            # Time vector for the steady state
            time_steady = np.arange(TT, Tmax)

            # All time series
            mean_c1 = RT_mean_time_series[TT:, 0]
            std_c1 = RT_std_time_series[TT:, 0]
            mean_c2, std_c2 = np.zeros_like(mean_c1), np.zeros_like(std_c1)
            mean_c3, std_c3 = np.zeros_like(mean_c1), np.zeros_like(std_c1)

            # A.1. Giant Component Evolution (Steady State, All Clusters)
            plt.figure(figsize=(6, 4))
            plt.title(f"Fraction of Active Nodes Over Time\n(Steady State, p={p:.2f})")

            # Cluster 1 (Giant)
            plt.plot(time_steady, mean_c1, label='Cluster 1 (Giant)', color='magenta', linewidth=2)
            # Shaded area for standard deviation (clipped between 0 and 1)
            plt.fill_between(time_steady,
                             np.clip(mean_c1 - std_c1, 0, 1),
                             np.clip(mean_c1 + std_c1, 0, 1),
                             color='magenta', alpha=0.2)

            # Cluster 2
            if RT_mean_time_series.shape[1] > 1:
                mean_c2 = RT_mean_time_series[TT:, 1]
                std_c2 = RT_std_time_series[TT:, 1]
                plt.plot(time_steady, mean_c2, label='Cluster 2', color='green', linewidth=2)
                plt.fill_between(time_steady,
                                 np.clip(mean_c2 - std_c2, 0, 1),
                                 np.clip(mean_c2 + std_c2, 0, 1),
                                 color='green', alpha=0.2)

            # Cluster 3
            if RT_mean_time_series.shape[1] > 2 and plot_third_cluster:
                mean_c3 = RT_mean_time_series[TT:, 2]
                std_c3 = RT_std_time_series[TT:, 2]
                plt.plot(time_steady, mean_c3, label='Cluster 3', color='blue', linewidth=2)
                plt.fill_between(time_steady,
                                 np.clip(mean_c3 - std_c3, 0, 1),
                                 np.clip(mean_c3 + std_c3, 0, 1),
                                 color='blue', alpha=0.2)
            plt.xlabel('Time (iterations)')
            plt.ylabel('Fraction of Active Nodes (R)')
            plt.xlim(TT, Tmax)
            plt.ylim(0, 1.05)
            plt.grid(True, linestyle='--', alpha=0.5)
            plt.legend()
            plt.tight_layout()
            plt.savefig(os.path.join(fig_dir, f"R_evolution_steady_p{p:.2f}.png"), dpi=400)
            plt.close()

            # A.2. Giant Component Evolution (Steady State, Cluster 1, Giant Component)
            plt.figure(figsize=(6, 4))
            plt.title(f"Fraction of Active Nodes Over Time\n(Steady State, p={p:.2f}, Giant Component)")
            plt.plot(time_steady, mean_c1, label='Cluster 1 (Giant)', color='magenta', linewidth=2)
            # Shaded area for standard deviation (clipped between 0 and 1)
            plt.fill_between(time_steady,
                             np.clip(mean_c1 - std_c1, 0, 1),
                             np.clip(mean_c1 + std_c1, 0, 1),
                             color='magenta', alpha=0.2)
            plt.xlabel('Time (iterations)')
            plt.ylabel('Fraction of Active Nodes (R)')
            plt.xlim(TT, Tmax)
            plt.ylim(0, 1.05)
            plt.grid(True, linestyle='--', alpha=0.5)
            plt.tight_layout()
            plt.savefig(os.path.join(fig_dir, f"Cl1_evolution_steady_p{p:.2f}.png"), dpi=400)
            plt.close()

            if RT_mean_time_series.shape[1] > 1:
                # A.3. Giant Component Evolution (Steady State, Cluster 2)
                plt.figure(figsize=(6, 4))
                plt.title(f"Fraction of Active Nodes Over Time\n(Steady State, p={p:.2f}, Cluster 2)")
                plt.plot(time_steady, mean_c2, label='Cluster 2', color='green', linewidth=2)
                plt.fill_between(time_steady,
                                 np.clip(mean_c2 - std_c2, 0, 1),
                                 np.clip(mean_c2 + std_c2, 0, 1),
                                 color='green', alpha=0.2)
                plt.xlabel('Time (iterations)')
                plt.ylabel('Fraction of Active Nodes (R)')
                plt.xlim(TT, Tmax)
                max_y2 = np.max(mean_c2 + std_c2)
                plt.ylim(0, max_y2 * 1.2 if max_y2 > 0 else 0.1)
                plt.grid(True, linestyle='--', alpha=0.5)
                plt.tight_layout()
                plt.savefig(os.path.join(fig_dir, f"Cl2_evolution_steady_p{p:.2f}.png"), dpi=400)
                plt.close()

                # A.4. Comparative Evolution (Cluster 1 vs 2) with Ratio Subplot
                # Figure with 2 subplots vertically stacked, sharing the X axis.
                # height_ratios=[3, 1] means the top plot is 3 times taller than the bottom one.
                fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(6, 5), sharex=True,
                                               gridspec_kw={'height_ratios': [3, 1.2]})

                # --- TOP PANEL: Absolute Sizes ---
                ax1.set_title(f"Cluster 1 & 2 Evolution with Ratio\n(Steady State, p={p:.2f})")

                # Plot Cluster 1 (Giant)
                ax1.plot(time_steady, mean_c1, label='Cluster 1 (Giant)', color='magenta', linewidth=2)
                ax1.fill_between(time_steady,
                                 np.clip(mean_c1 - std_c1, 0, 1),
                                 np.clip(mean_c1 + std_c1, 0, 1),
                                 color='magenta', alpha=0.2)

                # Plot Cluster 2
                ax1.plot(time_steady, mean_c2, label='Cluster 2', color='green', linewidth=2)
                ax1.fill_between(time_steady,
                                 np.clip(mean_c2 - std_c2, 0, 1),
                                 np.clip(mean_c2 + std_c2, 0, 1),
                                 color='green', alpha=0.2)

                ax1.set_ylabel('Fraction of Active Nodes (R)')
                ax1.set_ylim(0, 1.05)
                ax1.grid(True, linestyle='--', alpha=0.5)
                ax1.legend(loc='best')

                # --- BOTTOM PANEL: Ratio C2 / C1 ---
                # Safe division: np.where avoids ZeroDivisionError when mean_c1 is exactly 0
                with np.errstate(divide='ignore', invalid='ignore'):
                    ratio = np.where(mean_c1 > 0, mean_c2 / mean_c1, 0)

                # Plot the ratio as a solid black line to make it look analytical
                ax2.plot(time_steady, ratio, color='black', linewidth=1.5)

                ax2.set_xlabel('Time (iterations)')
                ax2.set_ylabel('Ratio C2/C1')

                # Dynamically adjust the Y-axis of the ratio so it always fits nicely,
                # but has a minimum ceiling of 0.1 to avoid microscopic noise scaling.
                max_ratio = np.nanmax(ratio)
                ax2.set_ylim(0, max(0.1, max_ratio * 1.2))
                ax2.grid(True, linestyle='--', alpha=0.5)

                # Remove the horizontal space between the two panels for a cohesive look
                plt.subplots_adjust(hspace=0.05)

                plt.savefig(os.path.join(fig_dir, f"C1_vs_C2_Ratio_steady_p{p:.2f}.png"), dpi=400)
                plt.close()

            if RT_mean_time_series.shape[1] > 2:
                # A.5. Giant Component Evolution (Steady State, Cluster 3)
                plt.figure(figsize=(6, 4))
                plt.title(f"Fraction of Active Nodes Over Time\n(Steady State, p={p:.2f}, Cluster 3)")
                plt.plot(time_steady, mean_c3, label='Cluster 3', color='blue', linewidth=2)
                plt.fill_between(time_steady,
                                 np.clip(mean_c3 - std_c3, 0, 1),
                                 np.clip(mean_c3 + std_c3, 0, 1),
                                 color='blue', alpha=0.2)
                plt.xlabel('Time (iterations)')
                plt.ylabel('Fraction of Active Nodes (R)')
                plt.xlim(TT, Tmax)
                max_y3 = np.max(mean_c3 + std_c3)
                plt.ylim(0, max_y3 * 1.2 if max_y3 > 0 else 0.1)
                plt.grid(True, linestyle='--', alpha=0.5)
                plt.tight_layout()
                plt.savefig(os.path.join(fig_dir, f"Cl3_evolution_steady_p{p:.2f}.png"), dpi=400)
                plt.close()

        print("-> Generating Per-Seed Spatial & Phase Space Plots...")
        if seed_angular_data and RT_mean_time_series.size > 0:
            for seed_name, spatial_metrics in seed_angular_data.items():
                # Only plot the spatial/phase diagrams for the FIRST seed to avoid redundancy
                if seed_name != seed_list[0]: continue

                ang_pos = spatial_metrics["angular_positions"]
                ang_width = spatial_metrics["angular_widths"]

                if seed_name not in seed_RT_dict:
                    continue
                RT_seed = seed_RT_dict[seed_name]

                seed_fig_dir = os.path.join(folder, seed_name, "figures")
                os.makedirs(seed_fig_dir, exist_ok=True)    # Just in case

                # B.1. Phase Space (R vs Average Angle for Cluster 1)
                plt.figure(figsize=(6, 4))
                plt.title("Phase Space: Size vs Angular Position (Cluster 1)")
                sc1 = plt.scatter(ang_pos[:, 0], RT_seed[:, 0], c=np.arange(Tmax), cmap='viridis', s=15, alpha=0.8)
                plt.colorbar(sc1, label='Time (iterations)')
                plt.xlabel('Average Angular Position (rad)')
                plt.ylabel('Fraction of Active Nodes (R)')
                plt.xlim(0, 2 * np.pi)
                plt.ylim(0, 1.0)
                plt.grid(True, linestyle='--', alpha=0.5)
                plt.tight_layout()
                plt.savefig(os.path.join(seed_fig_dir, f"PhaseSpace_Cluster1_p{p:.2f}.png"), dpi=400)
                plt.close()

                # C.1. Spatial position tracking (angular position vs time) of Cluster 1
                plt.figure(figsize=(6, 4))
                plt.title("Spatial Position Over Time (Cluster 1)")
                plt.plot(ang_pos[:, 0], 'mo', markersize=3, label='Cluster 1 (Giant)')
                plt.axvline(TT, color='gray', linestyle=':', alpha=0.5, label='Steady State Onset')
                plt.xlabel('Time (iterations)')
                plt.ylabel('Average Angular Position (rad)')
                plt.ylim(0, 2 * np.pi)
                plt.grid(True, linestyle=':', alpha=0.5)
                plt.legend(loc='upper right')
                plt.tight_layout()
                plt.savefig(os.path.join(seed_fig_dir, f"Position_Time_Cluster1_p{p:.2f}.png"), dpi=400)
                plt.close()

                if ang_pos.shape[1] > 1:
                    if RT_seed.shape[1] > 1:
                        # B.2. Phase Space (R vs Average Angle for Cluster 2)
                        plt.figure(figsize=(6, 4))
                        plt.title("Phase Space: Size vs Angular Position (Cluster 2)")
                        sc2 = plt.scatter(ang_pos[:, 1], RT_seed[:, 1], c=np.arange(Tmax), cmap='plasma', s=15,
                                          alpha=0.8)
                        plt.colorbar(sc2, label='Time (iterations)')
                        plt.xlabel('Average Angular Position (rad)')
                        plt.ylabel('Fraction of Active Nodes (R)')
                        plt.xlim(0, 2 * np.pi)
                        max_r2 = np.max(RT_seed[:, 1])
                        plt.ylim(0, max_r2 * 1.2 if max_r2 > 0 else 0.1)
                        plt.grid(True, linestyle='--', alpha=0.5)
                        plt.tight_layout()
                        plt.savefig(os.path.join(seed_fig_dir, f"PhaseSpace_Cluster2_p{p:.2f}.png"), dpi=400)
                        plt.close()

                    # C.2. Spatial position tracking (angular position vs time) of Cluster 2
                    plt.figure(figsize=(6, 4))
                    plt.title("Spatial Position Over Time (Cluster 2)")
                    plt.plot(ang_pos[:, 1], 'go', markersize=3, label='Cluster 2')
                    plt.axvline(TT, color='gray', linestyle=':', alpha=0.5, label='Steady State Onset')
                    plt.xlabel('Time (iterations)')
                    plt.ylabel('Average Angular Position (rad)')
                    plt.ylim(0, 2 * np.pi)
                    plt.grid(True, linestyle=':', alpha=0.5)
                    plt.legend(loc='upper right')
                    plt.tight_layout()
                    plt.savefig(os.path.join(seed_fig_dir, f"Position_Time_Cluster2_p{p:.2f}.png"), dpi=400)
                    plt.close()

                if ang_pos.shape[1] > 2:
                    if RT_seed.shape[1] > 2:
                        # B.3. Phase Space (R vs Average Angle for Cluster 3)
                        plt.figure(figsize=(6, 4))
                        plt.title("Phase Space: Size vs Angular Position (Cluster 3)")
                        sc3 = plt.scatter(ang_pos[:, 2], RT_seed[:, 2], c=np.arange(Tmax), cmap='cool', s=15, alpha=0.8)
                        plt.colorbar(sc3, label='Time (iterations)')
                        plt.xlabel('Average Angular Position (rad)')
                        plt.ylabel('Fraction of Active Nodes (R)')
                        plt.xlim(0, 2 * np.pi)
                        max_r3 = np.max(RT[:, 2])
                        plt.ylim(0, max_r3 + 0.05 if max_r3 > 0 else 0.1)
                        plt.grid(True, linestyle='--', alpha=0.5)
                        plt.tight_layout()
                        plt.savefig(os.path.join(seed_fig_dir, f"PhaseSpace_Cluster3_p{p:.2f}.png"), dpi=400)
                        plt.close()

                    # C.3. Spatial position tracking (angular position vs time) of Cluster 3
                    plt.figure(figsize=(6, 4))
                    plt.title("Spatial Position Over Time (Cluster 3)")
                    plt.plot(ang_pos[:, 2], 'bo', markersize=3, label='Cluster 3')
                    plt.axvline(TT, color='gray', linestyle=':', alpha=0.5, label='Steady State Onset')
                    plt.xlabel('Time (iterations)')
                    plt.ylabel('Average Angular Position (rad)')
                    plt.ylim(0, 2 * np.pi)
                    plt.grid(True, linestyle=':', alpha=0.5)
                    plt.legend(loc='upper right')
                    plt.tight_layout()
                    plt.savefig(os.path.join(seed_fig_dir, f"Position_Time_Cluster3_p{p:.2f}.png"), dpi=400)
                    plt.close()

                # B.4. Phase Space (R vs Average Angle for all 3 Clusters)
                plt.figure(figsize=(6, 4))
                plt.title("Phase Space: Size vs Angular Position (All Clusters)")

                # 1. Draw faint trajectory lines to clearly show the path over time
                plt.plot(ang_pos[:, 0], RT_seed[:, 0], color='purple', alpha=0.3, linewidth=1, zorder=1)
                if ang_pos.shape[1] > 1 and RT_seed.shape[1] > 1:
                    plt.plot(ang_pos[:, 1], RT_seed[:, 1], color='green', alpha=0.3, linewidth=1, zorder=1)
                if ang_pos.shape[1] > 2 and RT_seed.shape[1] > 2 and plot_third_cluster:
                    plt.plot(ang_pos[:, 2], RT_seed[:, 2], color='blue', alpha=0.3, linewidth=1, zorder=1)

                # 2. Scatter points using monochromatic sequential colormaps
                # Time is represented by how dark the color is (light -> dark)
                sc1 = plt.scatter(ang_pos[:, 0], RT_seed[:, 0], c=np.arange(Tmax), cmap='Purples',
                                  s=25, edgecolor='black', linewidth=0.5, alpha=0.9, zorder=2)
                if ang_pos.shape[1] > 1 and RT_seed.shape[1] > 1:
                    sc2 = plt.scatter(ang_pos[:, 1], RT_seed[:, 1], c=np.arange(Tmax), cmap='Greens',
                                      s=25, edgecolor='black', linewidth=0.5, alpha=0.9, zorder=2)
                if ang_pos.shape[1] > 2 and RT_seed.shape[1] > 2 and plot_third_cluster:
                    sc3 = plt.scatter(ang_pos[:, 2], RT_seed[:, 2], c=np.arange(Tmax), cmap='Blues',
                                      s=25, edgecolor='black', linewidth=0.5, alpha=0.9, zorder=2)

                # 3. Add a unified, neutral colorbar for Time
                # We create a dummy Grays scalar mappable so it doesn't favor any specific cluster color
                sm = plt.cm.ScalarMappable(cmap='Greys', norm=plt.Normalize(vmin=0, vmax=Tmax))
                cbar = plt.colorbar(sm, ax=plt.gca())
                cbar.set_label('Time (Iterations: Light -> Dark)')

                # 4. Create a custom legend for the clusters
                legend_elements = [
                    Line2D([0], [0], marker='o', color='w', markerfacecolor='purple', markersize=8,
                           label='Cluster 1 (Giant)'),

                ]
                if ang_pos.shape[1] > 1 and RT_seed.shape[1] > 1:
                    legend_elements.append(
                        Line2D([0], [0], marker='o', color='w', markerfacecolor='green', markersize=8,
                               label='Cluster 2'))
                if ang_pos.shape[1] > 2 and RT_seed.shape[1] > 2 and plot_third_cluster:
                    legend_elements.append(
                        Line2D([0], [0], marker='o', color='w', markerfacecolor='blue', markersize=8,
                               label='Cluster 3'))

                plt.legend(handles=legend_elements, loc='upper right')

                plt.xlabel('Average Angular Position (rad)')
                plt.ylabel('Fraction of Active Nodes (R)')
                plt.xlim(0, 2 * np.pi)
                plt.ylim(0, 1.05)
                plt.grid(True, linestyle='--', alpha=0.5)
                plt.tight_layout()
                plt.savefig(os.path.join(seed_fig_dir, f"PhaseSpace_All_Cluster_p{p:.2f}.png"), dpi=400)
                plt.close()

                # C.4. Spatial position tracking (angular position vs time) of all 3 Clusters
                plt.figure(figsize=(6, 4))
                plt.title("Spatial Position Over Time of All Clusters")
                plt.plot(ang_pos[:, 0], 'mo', markersize=3, label='Cluster 1 (Giant)')
                if ang_pos.shape[1] > 1:
                    plt.plot(ang_pos[:, 1], 'go', markersize=3, label='Cluster 2')
                if ang_pos.shape[1] > 2 and plot_third_cluster:
                    plt.plot(ang_pos[:, 2], 'bo', markersize=3, label='Cluster 3')
                plt.axvline(TT, color='gray', linestyle=':', alpha=0.5, label='Steady State Onset')
                plt.xlabel('Time (iterations)')
                plt.ylabel('Average Angular Position (rad)')
                plt.ylim(0, 2 * np.pi)
                plt.grid(True, linestyle='-', alpha=0.3)
                plt.legend(loc='upper right')
                plt.tight_layout()
                plt.savefig(os.path.join(seed_fig_dir, f"Position_Time_All_p{p:.2f}.png"), dpi=400)
                plt.close()

                # D.1. Spatial width tracking (pattern width vs time) of Cluster 1
                plt.figure(figsize=(6, 4))
                plt.title("Spatial Width Over Time (Cluster 1)")
                plt.plot(ang_width[:, 0], 'm-', linewidth=2, label='Cluster 1 (Giant)')
                plt.axvline(TT, color='gray', linestyle=':', alpha=0.5, label='Steady State Onset')
                plt.xlabel('Time (iterations)')
                plt.ylabel('Pattern Width (Circular Std) (rad)')
                plt.grid(True, linestyle=':', alpha=0.5)
                plt.legend(loc='upper right')
                plt.tight_layout()
                plt.savefig(os.path.join(seed_fig_dir, f"Width_Time_Cluster1_p{p:.2f}.png"), dpi=400)
                plt.close()

                if ang_width.shape[1] > 1:
                    # D.2. Spatial width tracking (pattern width vs time) of Cluster 2
                    plt.figure(figsize=(6, 4))
                    plt.title("Spatial Width Over Time (Cluster 2)")
                    plt.plot(ang_width[:, 1], 'g-', linewidth=2, label='Cluster 2')
                    plt.axvline(TT, color='gray', linestyle=':', alpha=0.5, label='Steady State Onset')
                    plt.xlabel('Time (iterations)')
                    plt.ylabel('Pattern Width (Circular Std) (rad)')
                    plt.grid(True, linestyle=':', alpha=0.5)
                    plt.legend(loc='upper right')
                    plt.tight_layout()
                    plt.savefig(os.path.join(seed_fig_dir, f"Width_Time_Cluster2_p{p:.2f}.png"), dpi=400)
                    plt.close()

                if ang_width.shape[1] > 2:
                    # D.3. Spatial width tracking (pattern width vs time) of Cluster 3
                    plt.figure(figsize=(6, 4))
                    plt.title("Spatial Width Over Time (Cluster 3)")
                    plt.plot(ang_width[:, 2], 'b-', linewidth=2, label='Cluster 3')
                    plt.axvline(TT, color='gray', linestyle=':', alpha=0.5, label='Steady State Onset')
                    plt.xlabel('Time (iterations)')
                    plt.ylabel('Pattern Width (Circular Std) (rad)')
                    plt.grid(True, linestyle=':', alpha=0.5)
                    plt.legend(loc='upper right')
                    plt.tight_layout()
                    plt.savefig(os.path.join(seed_fig_dir, f"Width_Time_Cluster3_p{p:.2f}.png"), dpi=400)
                    plt.close()

                # D.4. Spatial width tracking (pattern width vs time) of all 3 Clusters
                plt.figure(figsize=(6, 4))
                plt.title("Spatial Width Over Time of All Clusters")
                plt.plot(ang_width[:, 0], 'm-', linewidth=2, label='Cluster 1 (Giant)')
                if ang_width.shape[1] > 1:
                    plt.plot(ang_width[:, 1], 'g-', linewidth=2, label='Cluster 2')
                if ang_width.shape[1] > 2 and plot_third_cluster:
                    plt.plot(ang_width[:, 2], 'b-', linewidth=2, label='Cluster 3')
                plt.axvline(TT, color='gray', linestyle=':', alpha=0.5, label='Steady State Onset')
                plt.xlabel('Time (iterations)')
                plt.ylabel('Pattern Width (Circular Std) (rad)')
                plt.grid(True, linestyle='-', alpha=0.3)
                plt.legend(loc='upper right')
                plt.tight_layout()
                plt.savefig(os.path.join(seed_fig_dir, f"Width_Time_All_p{p:.2f}.png"), dpi=400)
                plt.close()

        # E. Spatiotemporal Raster Plot
        print("-> Generating Spatiotemporal Raster/Heatmaps...")
        if state_nodes_dict and nodes_coords_dict:
            first_seed = list(nodes_coords_dict.keys())[0]
            if nodes_coords_dict[first_seed].shape[1] == 1:
                for seed_name, state_nodes in state_nodes_dict.items():
                    # Skip redundant raster plots for the other seeds
                    if seed_name != seed_list[0]: continue
                    if seed_name not in nodes_coords_dict: continue
                    nodes_coords = nodes_coords_dict[seed_name]

                    seed_fig_dir = os.path.join(folder, seed_name, "figures")
                    os.makedirs(seed_fig_dir, exist_ok=True)  # Just in case

                    plt.figure(figsize=(8, 5))

                    # np.where searches automatically where state_nodes is True
                    # It returns two arrays: one with the time indices and another with the node indices of the active
                    # nodes
                    active_times, active_node_indices = np.where(state_nodes)

                    # We extract the exact spatial position 'y' of those active nodes
                    y_positions = nodes_coords[active_node_indices, 0]

                    # Draw all the points at the same time
                    # s=0.5 makes the points smaller, and alpha=0.8 gives them some transparency to better visualize
                    # overlaps
                    plt.scatter(active_times, y_positions, color='black', s=0.5, alpha=0.8)
                    plt.title(f"Giant Component Spatiotemporal Evolution (p={p:.2f})")
                    plt.xlabel('Time (iterations)')
                    plt.ylabel('Spatial Position (L)')
                    plt.xlim(0, Tmax)
                    plt.ylim(0, L)
                    plt.grid(True, linestyle='-', alpha=0.3, color='lightgray')
                    plt.tight_layout()
                    plt.savefig(os.path.join(seed_fig_dir, f"raster_plot_p{p:.2f}.png"), dpi=400)
                    plt.close()

            elif nodes_coords_dict[first_seed].shape[1] == 2:
                for seed_name, state_nodes in state_nodes_dict.items():
                    # Skip redundant raster plots for the other seeds
                    if seed_name != seed_list[0]: continue
                    if seed_name not in nodes_coords_dict: continue
                    nodes_coords = nodes_coords_dict[seed_name]

                    seed_fig_dir = os.path.join(folder, seed_name, "figures")
                    os.makedirs(seed_fig_dir, exist_ok=True)  # Just in case

                    plt.figure(figsize=(6, 6))

                    # We create a heatmap based on the frequency of activation of each node
                    activation_freq = np.sum(state_nodes, axis=0) / float(Tmax)

                    sc = plt.scatter(nodes_coords[:, 0], nodes_coords[:, 1], c=activation_freq,
                                     cmap='magma', s=3, alpha=0.6)
                    plt.colorbar(sc, label='Activation Frequency')
                    plt.title(f"Giant Component Spatial Activity Heatmap (p={p:.2f})")
                    plt.xlabel('X Position')
                    plt.ylabel('Y Position')
                    plt.xlim(0, Lx)
                    plt.ylim(0, Ly)
                    plt.grid(True, linestyle='--', alpha=0.3)
                    plt.tight_layout()
                    plt.savefig(os.path.join(seed_fig_dir, f"heatmap_2D_p{p:.2f}.png"), dpi=400)
                    plt.close()

# =============================================================================
# GLOBAL ANALYSIS (Comparisons across different 'p' values)
# =============================================================================
print("\n" + "=" * 60)
print("Generating Global Comparative Plots...")

# Dictionary to easily loop over both dimensions without duplicating plotting code
global_data_collections = {
    "1D": {
        "time_series": global_R_time_series_1D,
        "fluctuations": all_R_fluctuations_1D,
        "distances": steady_state_distances_1D,
        "R_vs_p": global_R_vs_p_1D
    },
    "RINGS": {
        "time_series": global_R_time_series_RINGS,
        "fluctuations": all_R_fluctuations_RINGS,
        "distances": steady_state_distances_RINGS,
        "R_vs_p": global_R_vs_p_RINGS
    },
    "2D": {
        "time_series": global_R_time_series_2D,
        "fluctuations": all_R_fluctuations_2D,
        "distances": steady_state_distances_2D,
        "R_vs_p": global_R_vs_p_2D
    }
}

for current_dim, g_data in global_data_collections.items():
    # Skip if no data exists for this dimension
    if not g_data["time_series"] and not g_data["R_vs_p"]:
        continue

    print(f"\n-> Generating global comparative plots for {current_dim}...")
    base_global_fig_dir = os.path.join(base_dirs[current_dim], "global_figures")

    # Identify unique ring resolutions in the data (will be [None] for 1D and 2D)
    if g_data["R_vs_p"]:
        # Extract unique, non-null ring values and sort them
        unique_rings = sorted(list(set(d.get('num_rings') for d in g_data["R_vs_p"])))
    else:
        unique_rings = [None]

    # Iterate over each resolution to isolate their global plots
    for ring_val in unique_rings:
        # 1. SETUP DIRECTORY AND TITLES
        if ring_val is not None:
            # RINGS model: Create subfolders for each resolution (e.g., global_figures/Nr_5/)
            global_fig_dir = os.path.join(base_global_fig_dir, f"Nr_{int(ring_val)}")
            dim_title_suffix = f"{current_dim}, Nr={int(ring_val)}, N={t_N_rings}"
        else:
            # 1D/2D models: Standard global directory
            global_fig_dir = base_global_fig_dir
            dim_N = t_N_1d if current_dim == "1D" else t_N_2d
            dim_title_suffix = f"{current_dim}, N={dim_N}"

        os.makedirs(global_fig_dir, exist_ok=True)

        # 2. FILTER DATA FOR THIS SPECIFIC RESOLUTION
        filt_ts = [d for d in g_data["time_series"] if d.get('num_rings') == ring_val]
        filt_fl = [d for d in g_data["fluctuations"] if d.get('num_rings') == ring_val]
        filt_di = [d for d in g_data["distances"] if d.get('num_rings') == ring_val]
        filt_rp = [d for d in g_data["R_vs_p"] if d.get('num_rings') == ring_val]

        # 3. GENERATE PLOTS USING FILTERED DATA
        # A. COMPARATIVE TIME EVOLUTION OF R FOR ALL THE GENERATED P
        if filt_ts:
            print(f"-> Generating global Time Dynamics comparison for {dim_title_suffix}...")
            plt.figure(figsize=(8, 5))

            # Sort the series by 'p' so the legend appears ordered
            sorted_ts = sorted(filt_ts, key=lambda x: x['p'])

            # Create a color palette to differentiate 'p' values
            colors = sns.color_palette("viridis", n_colors=len(sorted_ts))

            for i, data_series in enumerate(sorted_ts):
                plt.plot(data_series['time'], data_series['R'], color=colors[i],
                         linewidth=1.5, label=f"p = {data_series['p']:.2f}")

                if 'R_std' in data_series:
                    plt.fill_between(data_series['time'],
                                     np.clip(data_series['R'] - data_series['R_std'], 0, 1),
                                     np.clip(data_series['R'] + data_series['R_std'], 0, 1),
                                     color=colors[i], alpha=0.1)

            plt.title(f"Evolution of the Giant Component over Time ({dim_title_suffix})")
            plt.xlabel("Time (iterations)")
            plt.ylabel("Fraction of Active Nodes (R)")
            plt.ylim(0, 1.05)
            plt.grid(True, linestyle='--', alpha=0.5)

            # Move the legend outside the plot so it doesn't overlap the curves
            plt.legend(title="Control Parameter", bbox_to_anchor=(1.05, 1), loc='upper left')
            plt.tight_layout()
            plt.savefig(os.path.join(global_fig_dir, "global_R_vs_Time_comparison.png"), dpi=400)
            plt.close()

        # B. VIOLIN PLOT FOR R FLUCTUATIONS IN 1 DIMENSION
        if filt_fl:
            print(f"-> Generating global Fluctuations comparison for {dim_title_suffix}...")
            df_fluctuations = pd.DataFrame(filt_fl)
            df_fluctuations['p_label'] = df_fluctuations['p'].apply(lambda x: f"{x:.2f}")

            plt.figure(figsize=(8, 5))

            sns.violinplot(data=df_fluctuations, x='p_label', y='R', hue='p_label', palette='viridis',
                           inner=None, linewidth=1, density_norm='width', legend=False)
            sns.stripplot(data=df_fluctuations, x='p_label', y='R', size=2.5, color='black',
                          alpha=0.3, jitter=True, legend=False)

            plt.title(f"Steady State Fluctuations of R ({dim_title_suffix})")
            plt.xlabel("Control Parameter (p)")
            plt.ylabel("Fraction of Active Nodes (R)")
            plt.ylim(0, 1.05)
            plt.grid(True, linestyle='--', alpha=0.3)
            plt.tight_layout()
            plt.savefig(os.path.join(global_fig_dir, "global_violin_fluctuations_R.png"), dpi=400)
            plt.close()

        # C. DISTANCE VS P PLOT IN 1 DIMENSION
        if filt_di:
            print(f"-> Generating global Distance vs p comparison plot for {dim_title_suffix}...")
            df_distances = pd.DataFrame(filt_di).sort_values(by='p')
            plt.figure(figsize=(6, 4))

            # Plotting baseline t=0 (taking the mean of all t=0 distances as reference)
            avg_baseline = df_distances['dist_t0'].mean()
            plt.axhline(avg_baseline, color='gray', linestyle='--', linewidth=2,
                        label=f'Structural baseline (t=0): {avg_baseline:.2f}')

            if 'dist_tmax_std' in df_distances.columns:
                plt.errorbar(df_distances['p'], df_distances['dist_tmax'],
                             yerr=df_distances['dist_tmax_std'],
                             fmt='o-', color='darkorange', linewidth=2, markersize=6,
                             capsize=4, capthick=1.5, label='Steady State (t=Tmax)')
            else:
                # Fallback if no std is available, just plot the points without error bars
                plt.plot(df_distances['p'], df_distances['dist_tmax'], marker='o',
                         color='darkorange', linestyle='-', linewidth=2, markersize=6,
                         label='Steady State (t=Tmax)')

            plt.title(f"Steady State Topological Distance vs p ({dim_title_suffix})")
            plt.xlabel("Control Parameter (p)")
            plt.ylabel("Average Shortest Path (Hops)")
            plt.legend(loc='best')
            plt.grid(True, linestyle='--', alpha=0.6)
            plt.tight_layout()
            plt.savefig(os.path.join(global_fig_dir, "global_distance_vs_p.png"), dpi=400)
            plt.close()

        # D. BASELINE R VS P PLOT (SINGLE TARGET LINE)
        # This generates the fundamental R vs p plot for the target parameters regardless of comparison sweeps
        if filt_rp:
            if current_dim == "1D":
                target_df = [d for d in filt_rp if
                             round(d['c'], 3) == round(t_c_1d, 3) and
                             round(d['d0'], 3) == round(t_d0_1d, 3) and
                             d['Tmax'] == t_Tmax_1d]
            elif current_dim == "2D":
                target_df = [d for d in filt_rp if
                             round(d['c'], 3) == round(t_c_2d, 3) and
                             round(d['d0'], 3) == round(t_d0_2d, 3) and
                             d['Tmax'] == t_Tmax_2d]
            else:  # RINGS
                target_df = [d for d in filt_rp if
                             round(d['c'], 3) == round(t_c_rings, 3) and
                             round(d['cpos'], 3) == round(t_cpos_rings, 3) and
                             d['Tmax'] == t_Tmax_rings]

            df_base_rp = pd.DataFrame(target_df).sort_values(by='p')

            if not df_base_rp.empty:
                plt.figure(figsize=(6, 4))
                plt.errorbar(df_base_rp['p'], df_base_rp['R_mean'], yerr=df_base_rp['R_std'],
                             fmt='o-', color='magenta', linewidth=2.5, capsize=3, label='Target Baseline')

                plt.title(f"Baseline Giant Component (R) vs p ({dim_title_suffix})")
                plt.xlabel("Control Parameter (p)")
                plt.ylabel("Fraction of Active Nodes (R)")
                plt.ylim(0, 1.05)
                plt.grid(True, linestyle='--', alpha=0.6)
                plt.legend(loc='best')
                plt.tight_layout()
                plt.savefig(os.path.join(global_fig_dir, "global_baseline_R_vs_p.png"), dpi=400)
                plt.close()

        # E. R VS P COMPARISON PLOT (MULTIPLE LINES FOR DIFFERENT PARAMETERS)
        if do_param_comparison and filt_rp:
            print(f"-> Generating R vs p parameter comparison plot {dim_title_suffix}...")
            df_params = pd.DataFrame(filt_rp)

            # Automatically detect which parameters actually vary in your folders (excluding 'p' and 'R_mean')
            param_cols = ['c', 'cpos', 'cneg', 'd0', 'dr']
            varying_params = [col for col in param_cols if df_params[col].nunique() > 1]

            plt.figure(figsize=(8, 6))

            if not varying_params:
                # If no parameters varied (you only tested different p's for one network setup)
                grouped = df_params.groupby('p').mean(numeric_only=True).reset_index()
                y_err = grouped['R_std'] if 'R_std' in grouped.columns else None
                plt.errorbar(grouped['p'], grouped['R_mean'], yerr=y_err, fmt='o-',
                             linewidth=2, elinewidth=1, capsize=0, alpha=0.8,
                             color='magenta', label='Base parameters')
            else:
                # ADAPTIVE VISUAL STRATEGY BASED ON NUMBER OF VARYING PARAMETERS
                num_vars = len(varying_params)

                # Define visual scales available for mapping
                line_styles = ['-', '--', ':', '-.']
                markers = ['o', 's', '^', 'D', 'v', 'p', '*']

                # Create dynamic mappings for the varying parameters
                if num_vars == 1:
                    # 1 Variable: Use a sequential colormap (Intensity implies magnitude)
                    unique_p1 = sorted(df_params[varying_params[0]].unique())
                    colors = sns.color_palette("viridis", n_colors=len(unique_p1))
                    color_map = dict(zip(unique_p1, colors))

                elif num_vars >= 2:
                    # 2+ Variables: 1st is Color (Categorical), 2nd is Line Style
                    unique_p1 = sorted(df_params[varying_params[0]].unique())
                    colors = sns.color_palette("tab10", n_colors=len(unique_p1))
                    color_map = dict(zip(unique_p1, colors))

                    unique_p2 = sorted(df_params[varying_params[1]].unique())
                    # Use modulo to avoid IndexError if there are many unique values
                    style_map = {val: line_styles[i % len(line_styles)] for i, val in enumerate(unique_p2)}

                    if num_vars >= 3:
                        # 3+ Variables: 3rd is Marker shape
                        unique_p3 = sorted(df_params[varying_params[2]].unique())
                        marker_map = {val: markers[i % len(markers)] for i, val in enumerate(unique_p3)}

                # Group the data and plot using the mapped aesthetics
                for name, group in df_params.groupby(varying_params):
                    group = group.sort_values(by='p')

                    # Ensure 'name' is always a tuple for consistent unpacking
                    vals = name if isinstance(name, tuple) else (name,)

                    # Create a dynamic legend label
                    label = ", ".join([f"{var}={val}" for var, val in zip(varying_params, vals)])

                    # Resolve aesthetics based on the mappings created above
                    c_val = color_map[vals[0]] if num_vars >= 1 else 'magenta'
                    ls_val = style_map[vals[1]] if num_vars >= 2 else '-'
                    m_val = marker_map[vals[2]] if num_vars >= 3 else 'o'

                    # Extract error if available
                    y_err = group['R_std'] if 'R_std' in group.columns else None

                    # Plot with fine error bars (elinewidth=1) and no caps to prevent visual clutter
                    plt.errorbar(group['p'], group['R_mean'], yerr=y_err,
                                 marker=m_val, linestyle=ls_val, color=c_val,
                                 linewidth=2, elinewidth=1, capsize=0, alpha=0.8,
                                 label=label)

            plt.title(f"Steady State Giant Component (R) vs p ({dim_title_suffix})")
            plt.xlabel("Control Parameter (p)")
            plt.ylabel("Average Fraction of Active Nodes (R)")
            plt.ylim(0, 1.05)
            plt.grid(True, linestyle='--', alpha=0.6)

            # Put the legend outside the plot, scaled slightly smaller to fit complex labels
            plt.legend(title="Varying Parameters", bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
            plt.tight_layout()
            plt.savefig(os.path.join(global_fig_dir, "global_R_vs_p_comparison.png"), dpi=400)
            plt.close()

# =============================================================================
# CROSS-DIMENSIONAL ANALYSIS (PERCOLATION & TRANSITION)
# =============================================================================
print("\n" + "=" * 60)
print("Generating Cross-Dimensional Master Plots (Percolation)...")
cross_fig_dir = "./results/cross_dimensional_figures"
os.makedirs(cross_fig_dir, exist_ok=True)

# 1. Provide the exact target baseline models from the independently collected lists
baseline_1D = master_limit_1D
baseline_2D = master_limit_2D

# For RINGS, we extract from the global RINGS list matching the target probabilities
baseline_RINGS = [d for d in global_R_vs_p_RINGS if
                  round(d['c'], 3) == round(t_c_rings, 3) and
                  round(d['cpos'], 3) == round(t_cpos_rings, 3) and
                  round(d['cneg'], 3) == round(t_cneg_rings, 3)]

# Convert to dataframes
df1 = pd.DataFrame(baseline_1D).sort_values('p') if baseline_1D else pd.DataFrame()
df2 = pd.DataFrame(baseline_2D).sort_values('p') if baseline_2D else pd.DataFrame()
dfR = pd.DataFrame(baseline_RINGS)  # Do not sort yet, it has multiple num_rings

if not df1.empty or not df2.empty or not dfR.empty:

    unique_rings = sorted(dfR['num_rings'].dropna().unique()) if not dfR.empty else []
    # Create a nice sequential palette for the scalable rings (avoiding too light colors)
    ring_colors = sns.color_palette("GnBu", n_colors=len(unique_rings) + 2)

    # --- PLOT 1: MASTER R vs p (Parameter of Order) ---
    plt.figure(figsize=(8, 5))
    if not df1.empty:
        plt.errorbar(df1['p'], df1['R_mean'], yerr=df1['R_std'], fmt='o-',
                     color='purple', label='1D Limit (Ring)', linewidth=2, capsize=3, zorder=5)

    if not dfR.empty:
        for idx, r_val in enumerate(unique_rings):
            df_sub = dfR[dfR['num_rings'] == r_val].sort_values('p')
            plt.errorbar(df_sub['p'], df_sub['R_mean'], yerr=df_sub['R_std'], fmt='^-',
                         color=ring_colors[idx + 1], label=f'Rings (Nr={int(r_val)})', linewidth=1.5, zorder=4)

    if not df2.empty:
        plt.errorbar(df2['p'], df2['R_mean'], yerr=df2['R_std'], fmt='s-',
                     color='darkorange', label='2D Limit (Square)', linewidth=2, capsize=3, zorder=6)

    plt.title("Dimensional Shift of the Triadic Percolation Transition")
    plt.xlabel("Control Parameter (p)")
    plt.ylabel("Fraction of Active Nodes (R)")
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.savefig(os.path.join(cross_fig_dir, "master_R_vs_p.png"), dpi=400)
    plt.close()

    # --- PLOT 2: MASTER SUSCEPTIBILITY vs p ---
    plt.figure(figsize=(8, 5))
    if not df1.empty:
        plt.plot(df1['p'], df1['susceptibility'], marker='o',
                 color='purple', label='1D Limit (Ring)', linewidth=2, zorder=5)

    if not dfR.empty:
        for idx, r_val in enumerate(unique_rings):
            df_sub = dfR[dfR['num_rings'] == r_val].sort_values('p')
            plt.plot(df_sub['p'], df_sub['susceptibility'], marker='^',
                     color=ring_colors[idx + 1], label=f'Rings (Nr={int(r_val)})', linewidth=1.5, zorder=4)

    if not df2.empty:
        plt.plot(df2['p'], df2['susceptibility'], marker='s',
                 color='darkorange', label='2D Limit (Square)', linewidth=2, zorder=6)

    plt.title(r"Thermodynamic Susceptibility ($\chi$) vs Control Parameter")
    plt.xlabel("Control Parameter (p)")
    plt.ylabel(r"Susceptibility $\chi = N (\langle R^2 \rangle - \langle R \rangle^2)$")
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.savefig(os.path.join(cross_fig_dir, "master_susceptibility_vs_p.png"), dpi=400)
    plt.close()

    # --- PLOT 3: DUAL PANEL (R vs p AND Susceptibility vs p COMBINED) ---
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(9, 8), sharex=True,
                                   gridspec_kw={'height_ratios': [1, 1]})

    # TOP PANEL: Parameter of Order (R)
    ax1.set_title("Triadic Percolation: Parameter of Order and Susceptibility")
    if not df1.empty:
        ax1.errorbar(df1['p'], df1['R_mean'], yerr=df1['R_std'], fmt='o-', color='purple', label='1D Limit',
                     linewidth=2, zorder=5)
    if not dfR.empty:
        for idx, r_val in enumerate(unique_rings):
            df_sub = dfR[dfR['num_rings'] == r_val].sort_values('p')
            ax1.errorbar(df_sub['p'], df_sub['R_mean'], yerr=df_sub['R_std'], fmt='^-', color=ring_colors[idx + 1],
                         label=f'Rings (Nr={int(r_val)})', linewidth=1.5, zorder=4)
    if not df2.empty:
        ax1.errorbar(df2['p'], df2['R_mean'], yerr=df2['R_std'], fmt='s-', color='darkorange', label='2D Limit',
                     linewidth=2, zorder=6)

    ax1.set_ylabel("Active Nodes (R)")
    ax1.grid(True, linestyle='--', alpha=0.6)
    ax1.legend(bbox_to_anchor=(1.02, 1), loc='upper left')

    # BOTTOM PANEL: Susceptibility (Chi)
    if not df1.empty:
        ax2.plot(df1['p'], df1['susceptibility'], marker='o', color='purple', linewidth=2, zorder=5)
    if not dfR.empty:
        for idx, r_val in enumerate(unique_rings):
            df_sub = dfR[dfR['num_rings'] == r_val].sort_values('p')
            ax2.plot(df_sub['p'], df_sub['susceptibility'], marker='^', color=ring_colors[idx + 1], linewidth=1.5,
                     zorder=4)
    if not df2.empty:
        ax2.plot(df2['p'], df2['susceptibility'], marker='s', color='darkorange', linewidth=2, zorder=6)

    ax2.set_xlabel("Control Parameter (p)")
    ax2.set_ylabel(r"Susceptibility ($\chi$)")
    ax2.grid(True, linestyle='--', alpha=0.6)

    # Remove horizontal space between the two panels
    plt.subplots_adjust(hspace=0.05)
    plt.savefig(os.path.join(cross_fig_dir, "master_dual_percolation_plot.png"), dpi=400, bbox_inches='tight')
    plt.close()

    print(f"-> Cross-Dimensional master plots saved successfully in {cross_fig_dir}")

    # --- PLOT 4: CRITICAL PARAMETER (p_c) vs DIMENSIONALITY (Nr) ---
    # In Statistical Mechanics, p_c is strictly defined as the point where the susceptibility diverges (peaks).
    # We find this peak dynamically for each dimension and resolution.

    pc_1D = df1.loc[df1['susceptibility'].idxmax(), 'p'] if not df1.empty else None
    pc_2D = df2.loc[df2['susceptibility'].idxmax(), 'p'] if not df2.empty else None

    pc_rings = []
    nr_rings = []

    if not dfR.empty:
        for r_val in unique_rings:
            df_sub = dfR[dfR['num_rings'] == r_val]
            if not df_sub.empty:
                # Find the 'p' that maximizes susceptibility for this specific Nr
                pc_val = df_sub.loc[df_sub['susceptibility'].idxmax(), 'p']
                pc_rings.append(pc_val)
                nr_rings.append(r_val)

    if pc_rings or pc_1D is not None or pc_2D is not None:
        plt.figure(figsize=(8, 5))

        # Plot the scalable coupled rings as a dynamic trajectory connecting the points
        if pc_rings:
            plt.plot(nr_rings, pc_rings, marker='D', color='teal', linewidth=2.5, markersize=8,
                     label=r'Coupled Rings ($p_c$ vs $N_r$)', zorder=4)

        # Plot the 1D and 2D limits as infinite horizontal asymptotes (references)
        # This prevents point overlapping and shows the physical boundary limits of the phase transition.
        if pc_1D is not None:
            plt.axhline(pc_1D, color='purple', linestyle='--', linewidth=2, alpha=0.8,
                        label=f'1D Limit Asymptote ($p_c \\approx {pc_1D:.2f}$)', zorder=2)

        if pc_2D is not None:
            plt.axhline(pc_2D, color='darkorange', linestyle='--', linewidth=2, alpha=0.8,
                        label=f'2D Limit Asymptote ($p_c \\approx {pc_2D:.2f}$)', zorder=2)

        plt.title(r"Dimensional Crossover: Critical Threshold ($p_c$) vs Resolution")
        plt.xlabel("Number of Rings / Resolution ($N_r$)")
        plt.ylabel(r"Critical Control Parameter ($p_c$)")

        # Ensure x-axis only shows integer ring values
        plt.gca().xaxis.set_major_locator(plt.MaxNLocator(integer=True))

        plt.grid(True, linestyle=':', alpha=0.6)
        plt.legend(loc='best')
        plt.tight_layout()
        plt.savefig(os.path.join(cross_fig_dir, "master_pc_vs_Nr.png"), dpi=400)
        plt.close()

print("\n" + "=" * 60)
print(" ALL ANALYSIS COMPLETED SUCCESSFULLY!")
print("=" * 60 + "\n")